### ISSUE TITLE
Object Overlapping and Self Overlapping Bug

### ISSUE THREAD

**Issue by Garrettorious** [Flafla2/Generic-Raymarch-Unity#2]
when viewing shapes overlapping other shapes or even themselves at extreme angles, strange artifacts tend to occur. It's best explained with pictures.
Maybe I'm just misunderstanding and this is the nature of an acceptably fast step size, but it seems pretty strange, such as the exponential artifact on the cube.

![image](https://cloud.githubusercontent.com/assets/10536742/19495599/db374cb8-9538-11e6-826a-3e41f0556da3.png)

![thing](https://cloud.githubusercontent.com/assets/10536742/19495835/ddc45f56-9539-11e6-9437-da26a053cbc6.JPG)

![thing2](https://cloud.githubusercontent.com/assets/10536742/19495839/def629b8-9539-11e6-8e62-e39051821826.JPG)

**Comment by mmmovania** [comment]
This is an under/oversampling issue. Change line 142 in RaymarchGeneric.shader i.e. this line
`if(d.x < 0.001)`
to this
`if(d.x < 0.005)`
Note that this is still going to show some artifacts but those will be negligible as compared to using the initial values. 
if you reduce the value to d.x < 0.01 then you will remove this artifiact but the shading will look toonish with a lot of banding.

See if this helps.

**Comment by Flafla2** [comment]
I'm closing this as @mmmovania's answer is correct.
